apiVersion: v1
kind: Service
metadata:
  name: nkpdemo-service
spec:
  type: NodePort
  selector:
    app: nkpdemo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30946 # Optional: If you remove this line, Kubernetes will randomly assign a port between 30000-32767.