apiVersion: apps/v1
kind: Deployment
metadata:
  name: nkpdemo-deployment
  labels:
    app: nkpdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nkpdemo
  template:
    metadata:
      labels:
        app: nkpdemo
    spec:
      containers:
      - name: nkpdemo-container
        image: nginx
        volumeMounts: 
        - name: html-volume
          mountPath: /usr/share/nginx/html

      volumes:
      - name: html-volume
        configMap:
          name: nkpdemo-configmap
